cargo-features = ["profile-rustflags"]
[package]
name = "audio_path_tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"

[profile.dev]
rustflags = ["-D", "missing_return"]

[profile.release]
rustflags = ["-D", "missing_return"]
